"""
Django settings for my_blog project.

Generated by 'django-admin startproject' using Django 3.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0wf6gd0!7ji-!ths=kks8=*pdqy2-)i2&xkzu(4xzlm!xk056_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bootstrap_modal_forms',
    'django_private_chat2.apps.DjangoPrivateChat2Config',
    'widget_tweaks',
    'password_reset',
    'article',
    'bootstrap4',
    'users',
    'comment',
    'taggit',
    'ckeditor',
    'webpush',
    'channels',
    'chat',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'my_blog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

WEBPUSH_SETTINGS = {
  "VAPID_PUBLIC_KEY": "BK21QvpY_U3M3NvR8ZPOrpXzyqntrveTUfZ1B2_c9Qeh0W9gvI88SldKh47bYCeuyos6RQoH1fjMoCpB_xtkhq0",
  "VAPID_PRIVATE_KEY": "LEZFzFwAT3SNjgVZiAQvYftm2HKiGbgyBxCNFHAS4_4",
  "VAPID_ADMIN_EMAIL": "uestcliyu@163.com"
}
# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

BOOTSTRAP4 = {
  'include_jquery': True,
  }
if os.getcwd() == '/app':
  import dj_database_url
  DATABASES = {
    'default': dj_database_url.config(default='postgres://localhost')
  }
  SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
  ALLOWED_HOSTS = ['*']
  BASE_DIR = os.path.dirname(os.path.abspath(__file__))
  STATIC_ROOT = 'staticfiles'
  STATICFILES_DIRS = (
      os.path.join(BASE_DIR, "static"),
  )

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
)
#EMAIL_HOST = 'smtp.163.com'
#EMAIL_HOST_USER = 'example@163.com'
#EMAIL_HOST_PASSWORD = ''
#EMAIL_PORT = 465
#EMAIL_USE_SSL = True
#DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
LOGIN_REDIRECT_URL = '/'
CKEDITOR_CONFIGS = {
  'default': {
    'width':'auto',
    'toolbar':'full',
    'extraPlugins':','.join([
    'prism',  
    'uploadimage', # the upload image feature
        # your extra plugins here
    'div',
    'autolink',
    'autoembed',
    'embedsemantic',
    'autogrow',
    # 'devtools',
    'widget',
    'lineutils',
    'clipboard',
    'dialog',
    'dialogui',
    'elementspath',
    'codesnippet']),
  }
}

ASGI_APPLICATION = "my_blog.asgi.application"
WSGI_APPLICATION = 'my_blog.wsgi.application'
CHANNEL_LAYERS = {
  "default": {
    "BACKEND": "channels.layers.InMemoryChannelLayer"
  }
}
#CHANNEL_LAYERS = {
#  "default": {
#    "BACKEND": "channels_redis.core.RedisChannelLayer",
#    "CONFIG": {
#      "hosts": [("127.0.0.1", 6379)],
#    },
#  },
#}

#SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # 引擎（默认）
#SESSION_COOKIE_NAME = "sessionid"  # Session的cookie保存在浏览器上时的key，即：sessionid＝随机字符串（默认）
#SESSION_COOKIE_PATH = "/"  # Session的cookie保存的路径（默认）
#SESSION_COOKIE_DOMAIN = None  # Session的cookie保存的域名（默认）
#SESSION_COOKIE_SECURE = False  # 是否Https传输cookie（默认）
#SESSION_COOKIE_HTTPONLY = True  # 是否Session的cookie只支持http传输（默认）
#SESSION_COOKIE_AGE = 1209600  # Session的cookie失效日期（2周）（默认）
#SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # 是否关闭浏览器使得Session过期（默认）
#SESSION_SAVE_EVERY_REQUEST = False  # 是否每次请求都保存Session，默认修改之后才保存（默认）