# Generated by Django 3.2.8 on 2021-11-01 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_people'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='people',
            options={'ordering': ('-created',), 'verbose_name_plural': 'people'},
        ),
    ]
