# Generated by Django 3.2.8 on 2021-11-01 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20211101_1453'),
    ]

    operations = [
        migrations.DeleteModel(
            name='People',
        ),
    ]
