# Generated by Django 3.2.8 on 2021-11-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='pic',
            field=models.ImageField(upload_to='banner/%Y%m%d', verbose_name='轮播图'),
        ),
    ]
