# Generated by Django 3.2.8 on 2021-11-05 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_alter_banner_pic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ('-create_time', '-idx')},
        ),
    ]
