# Generated by Django 3.2.8 on 2021-11-08 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_events'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'ordering': ('-start_time',)},
        ),
    ]
