# Generated by Django 3.2.8 on 2021-11-08 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_alter_events_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
