# Generated by Django 3.2.8 on 2021-11-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0015_rename_event_name_event_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
