# Generated by Django 3.2.8 on 2021-11-11 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0018_auto_20211110_1710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('start_time',)},
        ),
    ]
