# Generated by Django 3.2.8 on 2021-11-11 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0019_alter_event_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='create_time',
        ),
    ]
